# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: srlTest@0
  name: LRC
  inputs:
    serverEndpoint: 'LRC'
    tenantid: '978594865'
    projectid: '1'
    testid: '1084'
- script: |
    echo Run ID of LRC run ${LRC.LRC_RUN_ID}
    echo See https://aka.ms/yaml
  displayName: 'Catch the run ID of the LRC run'
